# Generated by Django 3.1.3 on 2021-08-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=20)),
                ('classe', models.TextField(max_length=100)),
                ('groupe', models.TextField(max_length=100)),
                ('nom', models.TextField(max_length=100)),
                ('prenom', models.TextField(max_length=100)),
            ],
        ),
    ]
